swagger: '2.0'

info:
  version: 0.1.0
  title: "Session service."
  description: "Microservice for managing user session."

consumes:
  - application/json
produces:
  - application/json

basePath: /session/api/v1

security:
  - cookieKey: [ ]

securityDefinitions:

  cookieKey:
    description: Session auth inside cookie.
    type: apiKey
    in: header
    name: Cookie

definitions:

  LoginParam:
    type: object
    required:
      - email
      - password
    properties:
      email:
        $ref: '#/definitions/Email'
      password:
        $ref: '#/definitions/Password'

  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  Email:
    type: string
    format: email
    minLength: 1
    maxLength: 255

  Password:
    type: string
    format: password
    minLength: 8
    maxLength: 100

  UserID:
    type: integer
    format: int32

  Username:
    type: string
    minLength: 1
    maxLength: 30

  User:
    type: object
    required:
      - id
      - username
      - email
    properties:
      id:
        $ref: '#/definitions/UserID'
      username:
        $ref: '#/definitions/Username'
      email:
        $ref: '#/definitions/Email'

responses:

  GenericError:
    description: Generic error response.
    schema:
      $ref: '#/definitions/Error'

  NoContent:
    description: The server successfully processed the request and is not returning any content.

paths:

  /login:
    post:
      operationId: login
      description: Login for user.
      security: [ ]
      parameters:
        - name: args
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginParam'
      responses:
        200:
          description: OK
          headers:
            Set-Cookie:
              description: Session auth.
              type: string
          schema:
            $ref: '#/definitions/User'
        default: { $ref: '#/responses/GenericError' }

  /logout:
    post:
      operationId: logout
      description: Logout for user.
      responses:
        204: { $ref: '#/responses/NoContent' }
        default: { $ref: '#/responses/GenericError' }
