name: CI_SESSION

on:
  push:
    paths:
      - 'internal/modules/session/*'
    branches:
      - main
  pull_request:
    paths:
      - 'internal/modules/session/*'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: go test -race ./internal/modules/session/...